import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('Seeding quizzes...');

    const quizzes = [
        {
            moduleId: '904a8d6d-c757-468a-9bab-121341f6d012',
            title: 'Bilangan Cacah Sampai 1000 Quiz',
            timeLimitSeconds: 300,
            passingScore: 70,
            maxXp: 100,
            isPublished: true,
            questions: [
                {
                    questionText: "Lambang bilangan dari 'tiga ratus lima belas' adalah...",
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 1,
                    options: [
                        { optionText: '305', isCorrect: false, explanation: '' },
                        { optionText: '315', isCorrect: true, explanation: '' },
                        { optionText: '351', isCorrect: false, explanation: '' },
                        { optionText: '350', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Angka 7 pada bilangan 872 menempati nilai tempat...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 2,
                    options: [
                        { optionText: 'Satuan', isCorrect: false, explanation: '' },
                        { optionText: 'Puluhan', isCorrect: true, explanation: '' },
                        { optionText: 'Ratusan', isCorrect: false, explanation: '' },
                        { optionText: 'Ribuan', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 400 + 50 + 6 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 3,
                    options: [
                        { optionText: '456', isCorrect: true, explanation: '' },
                        { optionText: '465', isCorrect: false, explanation: '' },
                        { optionText: '546', isCorrect: false, explanation: '' },
                        { optionText: '406', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Bilangan di antara 567 dan 569 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 4,
                    options: [
                        { optionText: '566', isCorrect: false, explanation: '' },
                        { optionText: '568', isCorrect: true, explanation: '' },
                        { optionText: '570', isCorrect: false, explanation: '' },
                        { optionText: '565', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Tanda yang tepat untuk membandingkan 345 ... 354 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 5,
                    options: [
                        { optionText: '>', isCorrect: false, explanation: '' },
                        { optionText: '<', isCorrect: true, explanation: '' },
                        { optionText: '=', isCorrect: false, explanation: '' },
                        { optionText: '≥', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Selisih antara 500 dan 200 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 6,
                    options: [
                        { optionText: '100', isCorrect: false, explanation: '' },
                        { optionText: '200', isCorrect: false, explanation: '' },
                        { optionText: '300', isCorrect: true, explanation: '' },
                        { optionText: '400', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Urutan bilangan 234, 214, 254 dari yang terbesar adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 7,
                    options: [
                        { optionText: '214, 234, 254', isCorrect: false, explanation: '' },
                        { optionText: '254, 234, 214', isCorrect: true, explanation: '' },
                        { optionText: '234, 254, 214', isCorrect: false, explanation: '' },
                        { optionText: '254, 214, 234', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: '3 ratusan + 0 puluhan + 9 satuan menjadi bilangan...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 8,
                    options: [
                        { optionText: '390', isCorrect: false, explanation: '' },
                        { optionText: '309', isCorrect: true, explanation: '' },
                        { optionText: '903', isCorrect: false, explanation: '' },
                        { optionText: '3009', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 150 + 250 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 9,
                    options: [
                        { optionText: '300', isCorrect: false, explanation: '' },
                        { optionText: '350', isCorrect: false, explanation: '' },
                        { optionText: '400', isCorrect: true, explanation: '' },
                        { optionText: '450', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: "Lambang bilangan dari 'sembilan ratus dua' adalah...",
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 10,
                    options: [
                        { optionText: '920', isCorrect: false, explanation: '' },
                        { optionText: '902', isCorrect: true, explanation: '' },
                        { optionText: '209', isCorrect: false, explanation: '' },
                        { optionText: '9002', isCorrect: false, explanation: '' },
                    ],
                },
            ],
        },
        {
            moduleId: '5b538868-8ecd-42dd-853f-9300b52d842f',
            title: 'Penjumlahan Dan Pengurangan Sampai 1000 Quiz',
            timeLimitSeconds: 300,
            passingScore: 70,
            maxXp: 100,
            isPublished: true,
            questions: [
                {
                    questionText: 'Hasil dari 345 + 123 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 1,
                    options: [
                        { optionText: '458', isCorrect: false, explanation: '' },
                        { optionText: '468', isCorrect: true, explanation: '' },
                        { optionText: '478', isCorrect: false, explanation: '' },
                        { optionText: '488', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 560 - 240 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 2,
                    options: [
                        { optionText: '310', isCorrect: false, explanation: '' },
                        { optionText: '320', isCorrect: true, explanation: '' },
                        { optionText: '330', isCorrect: false, explanation: '' },
                        { optionText: '340', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Ibu membeli 250 gram terigu dan 150 gram gula. Total beratnya adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 3,
                    options: [
                        { optionText: '300 gram', isCorrect: false, explanation: '' },
                        { optionText: '350 gram', isCorrect: false, explanation: '' },
                        { optionText: '400 gram', isCorrect: true, explanation: '' },
                        { optionText: '450 gram', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 458 + 215 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 4,
                    options: [
                        { optionText: '663', isCorrect: false, explanation: '' },
                        { optionText: '673', isCorrect: true, explanation: '' },
                        { optionText: '683', isCorrect: false, explanation: '' },
                        { optionText: '693', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 700 - 325 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 5,
                    options: [
                        { optionText: '365', isCorrect: false, explanation: '' },
                        { optionText: '375', isCorrect: true, explanation: '' },
                        { optionText: '385', isCorrect: false, explanation: '' },
                        { optionText: '395', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Paman punya 450 mangga, dijual 300 buah. Sisa mangga adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 6,
                    options: [
                        { optionText: '100', isCorrect: false, explanation: '' },
                        { optionText: '150', isCorrect: true, explanation: '' },
                        { optionText: '200', isCorrect: false, explanation: '' },
                        { optionText: '250', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 125 + 200 - 50 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 7,
                    options: [
                        { optionText: '225', isCorrect: false, explanation: '' },
                        { optionText: '250', isCorrect: false, explanation: '' },
                        { optionText: '275', isCorrect: true, explanation: '' },
                        { optionText: '300', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Jika 500 - n = 200, maka n adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 8,
                    options: [
                        { optionText: '100', isCorrect: false, explanation: '' },
                        { optionText: '200', isCorrect: false, explanation: '' },
                        { optionText: '300', isCorrect: true, explanation: '' },
                        { optionText: '400', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Jarak 800m, sudah ditempuh 350m. Sisa jarak adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 9,
                    options: [
                        { optionText: '350m', isCorrect: false, explanation: '' },
                        { optionText: '400m', isCorrect: false, explanation: '' },
                        { optionText: '450m', isCorrect: true, explanation: '' },
                        { optionText: '500m', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: '333 + 444 = ...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 10,
                    options: [
                        { optionText: '666', isCorrect: false, explanation: '' },
                        { optionText: '777', isCorrect: true, explanation: '' },
                        { optionText: '888', isCorrect: false, explanation: '' },
                        { optionText: '999', isCorrect: false, explanation: '' },
                    ],
                },
            ],
        },
        {
            moduleId: '64eceff3-4ab6-425f-bc55-2f6d79ecf2f2',
            title: 'Pecahan Quiz',
            timeLimitSeconds: 300,
            passingScore: 70,
            maxXp: 100,
            isPublished: true,
            questions: [
                {
                    questionText: 'Bagian yang diarsir dari 4 kotak jika 1 kotak diarsir adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 1,
                    options: [
                        { optionText: '1/2', isCorrect: false, explanation: '' },
                        { optionText: '1/3', isCorrect: false, explanation: '' },
                        { optionText: '1/4', isCorrect: true, explanation: '' },
                        { optionText: '2/4', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: "Pecahan 'seperdua' ditulis dengan lambang...",
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 2,
                    options: [
                        { optionText: '1/2', isCorrect: true, explanation: '' },
                        { optionText: '1/3', isCorrect: false, explanation: '' },
                        { optionText: '2/1', isCorrect: false, explanation: '' },
                        { optionText: '2/2', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Pada pecahan 3/4, angka 3 disebut...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 3,
                    options: [
                        { optionText: 'Pembilang', isCorrect: true, explanation: '' },
                        { optionText: 'Penyebut', isCorrect: false, explanation: '' },
                        { optionText: 'Hasil', isCorrect: false, explanation: '' },
                        { optionText: 'Satuan', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Manakah yang lebih besar, 1/2 atau 1/4?',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 4,
                    options: [
                        { optionText: '1/2', isCorrect: true, explanation: '' },
                        { optionText: '1/4', isCorrect: false, explanation: '' },
                        { optionText: 'Sama saja', isCorrect: false, explanation: '' },
                        { optionText: 'Tidak dapat ditentukan', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Satu semangka dipotong menjadi 8 bagian. Adik makan 2 bagian. Pecahannya adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 5,
                    options: [
                        { optionText: '1/8', isCorrect: false, explanation: '' },
                        { optionText: '2/8', isCorrect: true, explanation: '' },
                        { optionText: '8/2', isCorrect: false, explanation: '' },
                        { optionText: '4/8', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Pecahan 2/4 senilai dengan...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 6,
                    options: [
                        { optionText: '1/2', isCorrect: true, explanation: '' },
                        { optionText: '1/3', isCorrect: false, explanation: '' },
                        { optionText: '1/5', isCorrect: false, explanation: '' },
                        { optionText: '2/3', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 1/4 + 2/4 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 7,
                    options: [
                        { optionText: '1/4', isCorrect: false, explanation: '' },
                        { optionText: '2/4', isCorrect: false, explanation: '' },
                        { optionText: '3/4', isCorrect: true, explanation: '' },
                        { optionText: '4/4', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 5/8 - 2/8 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 8,
                    options: [
                        { optionText: '1/8', isCorrect: false, explanation: '' },
                        { optionText: '2/8', isCorrect: false, explanation: '' },
                        { optionText: '3/8', isCorrect: true, explanation: '' },
                        { optionText: '4/8', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Pecahan sepertiga dilambangkan dengan...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 9,
                    options: [
                        { optionText: '3/1', isCorrect: false, explanation: '' },
                        { optionText: '1/3', isCorrect: true, explanation: '' },
                        { optionText: '3/3', isCorrect: false, explanation: '' },
                        { optionText: '1/4', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Ibu memotong kue menjadi 6 bagian. 3 bagian dimakan. Sisanya adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 10,
                    options: [
                        { optionText: '1/6', isCorrect: false, explanation: '' },
                        { optionText: '2/6', isCorrect: false, explanation: '' },
                        { optionText: '3/6', isCorrect: true, explanation: '' },
                        { optionText: '4/6', isCorrect: false, explanation: '' },
                    ],
                },
            ],
        }, {
            moduleId: '625757ff-9d14-4b6d-ab5c-5da1c72e56f5',
            title: 'KPK Dan FPB Quiz',
            timeLimitSeconds: 300,
            passingScore: 70,
            maxXp: 100,
            isPublished: true,
            questions: [
                {
                    questionText: 'Kelipatan dari 4 antara 10 dan 20 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 1,
                    options: [
                        { optionText: '12, 16', isCorrect: true, explanation: '' },
                        { optionText: '12, 16, 20', isCorrect: false, explanation: '' },
                        { optionText: '14, 18', isCorrect: false, explanation: '' },
                        { optionText: '8, 12, 16', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Faktor dari 12 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 2,
                    options: [
                        { optionText: '1, 2, 3, 4, 6, 12', isCorrect: true, explanation: '' },
                        { optionText: '2, 3, 4, 6', isCorrect: false, explanation: '' },
                        { optionText: '1, 2, 4, 12', isCorrect: false, explanation: '' },
                        { optionText: '1, 3, 6, 12', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Faktorisasi prima dari bilangan 20 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 3,
                    options: [
                        { optionText: '2 × 10', isCorrect: false, explanation: '' },
                        { optionText: '2² × 5', isCorrect: true, explanation: '' },
                        { optionText: '4 × 5', isCorrect: false, explanation: '' },
                        { optionText: '2 × 2 × 10', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'KPK dari 6 dan 8 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 4,
                    options: [
                        { optionText: '12', isCorrect: false, explanation: '' },
                        { optionText: '18', isCorrect: false, explanation: '' },
                        { optionText: '24', isCorrect: true, explanation: '' },
                        { optionText: '48', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'FPB dari 15 dan 25 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 5,
                    options: [
                        { optionText: '3', isCorrect: false, explanation: '' },
                        { optionText: '5', isCorrect: true, explanation: '' },
                        { optionText: '15', isCorrect: false, explanation: '' },
                        { optionText: '25', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Budi les 4 hari sekali, Andi 6 hari sekali. Mereka les bersama tiap...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 6,
                    options: [
                        { optionText: '10 hari', isCorrect: false, explanation: '' },
                        { optionText: '12 hari', isCorrect: true, explanation: '' },
                        { optionText: '18 hari', isCorrect: false, explanation: '' },
                        { optionText: '24 hari', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: '20 apel dan 30 jeruk dibagi ke wadah sama banyak. Wadah maksimal...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 7,
                    options: [
                        { optionText: '5', isCorrect: false, explanation: '' },
                        { optionText: '10', isCorrect: true, explanation: '' },
                        { optionText: '15', isCorrect: false, explanation: '' },
                        { optionText: '20', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Bilangan prima antara 10 dan 20 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 8,
                    options: [
                        { optionText: '11, 13, 15, 17, 19', isCorrect: false, explanation: '' },
                        { optionText: '11, 13, 17, 19', isCorrect: true, explanation: '' },
                        { optionText: '11, 15, 19', isCorrect: false, explanation: '' },
                        { optionText: '13, 15, 17', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'KPK dari 3, 4, dan 6 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 9,
                    options: [
                        { optionText: '6', isCorrect: false, explanation: '' },
                        { optionText: '12', isCorrect: true, explanation: '' },
                        { optionText: '24', isCorrect: false, explanation: '' },
                        { optionText: '36', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'FPB dari 18, 24, dan 30 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 10,
                    options: [
                        { optionText: '3', isCorrect: false, explanation: '' },
                        { optionText: '4', isCorrect: false, explanation: '' },
                        { optionText: '6', isCorrect: true, explanation: '' },
                        { optionText: '12', isCorrect: false, explanation: '' },
                    ],
                },
            ],
        },
        {
            moduleId: 'b48c659c-8eb2-4a8e-9004-0ebea9038c14',
            title: 'Pecahan Dan Desimal Quiz',
            timeLimitSeconds: 300,
            passingScore: 70,
            maxXp: 100,
            isPublished: true,
            questions: [
                {
                    questionText: 'Hasil dari 1/2 × 1/3 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 1,
                    options: [
                        { optionText: '1/5', isCorrect: false, explanation: '' },
                        { optionText: '1/6', isCorrect: true, explanation: '' },
                        { optionText: '2/5', isCorrect: false, explanation: '' },
                        { optionText: '2/6', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 3/4 : 1/2 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 2,
                    options: [
                        { optionText: '3/8', isCorrect: false, explanation: '' },
                        { optionText: '3/2', isCorrect: true, explanation: '' },
                        { optionText: '1/2', isCorrect: false, explanation: '' },
                        { optionText: '2/3', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 0,5 × 0,4 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 3,
                    options: [
                        { optionText: '0,2', isCorrect: true, explanation: '' },
                        { optionText: '0,02', isCorrect: false, explanation: '' },
                        { optionText: '2,0', isCorrect: false, explanation: '' },
                        { optionText: '0,8', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Bentuk persen dari 1/4 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 4,
                    options: [
                        { optionText: '10%', isCorrect: false, explanation: '' },
                        { optionText: '20%', isCorrect: false, explanation: '' },
                        { optionText: '25%', isCorrect: true, explanation: '' },
                        { optionText: '50%', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: '20% dari 50.000 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 5,
                    options: [
                        { optionText: '5.000', isCorrect: false, explanation: '' },
                        { optionText: '10.000', isCorrect: true, explanation: '' },
                        { optionText: '15.000', isCorrect: false, explanation: '' },
                        { optionText: '20.000', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 1,5 + 0,25 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 6,
                    options: [
                        { optionText: '1,30', isCorrect: false, explanation: '' },
                        { optionText: '1,75', isCorrect: true, explanation: '' },
                        { optionText: '2,00', isCorrect: false, explanation: '' },
                        { optionText: '1,50', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 2,4 : 0,6 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 7,
                    options: [
                        { optionText: '0,4', isCorrect: false, explanation: '' },
                        { optionText: '4', isCorrect: true, explanation: '' },
                        { optionText: '40', isCorrect: false, explanation: '' },
                        { optionText: '2', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Pecahan 1/2 jika diubah ke bentuk desimal adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 8,
                    options: [
                        { optionText: '0,2', isCorrect: false, explanation: '' },
                        { optionText: '0,5', isCorrect: true, explanation: '' },
                        { optionText: '0,05', isCorrect: false, explanation: '' },
                        { optionText: '0,25', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Desimal 0,75 jika diubah ke bentuk pecahan adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 9,
                    options: [
                        { optionText: '1/2', isCorrect: false, explanation: '' },
                        { optionText: '1/4', isCorrect: false, explanation: '' },
                        { optionText: '3/4', isCorrect: true, explanation: '' },
                        { optionText: '2/3', isCorrect: false, explanation: '' },
                    ],
                },
                {
                    questionText: 'Hasil dari 1 - 0,3 adalah...',
                    imageUrl: null,
                    timeLimitSeconds: 30,
                    baseXp: 10,
                    orderIndex: 10,
                    options: [
                        { optionText: '0,7', isCorrect: true, explanation: '' },
                        { optionText: '0,6', isCorrect: false, explanation: '' },
                        { optionText: '0,3', isCorrect: false, explanation: '' },
                        { optionText: '0,8', isCorrect: false, explanation: '' },
                    ],
                },
            ],
        }
    ];

    for (const quizData of quizzes) {
        await prisma.quiz.create({
            data: {
                moduleId: quizData.moduleId,
                title: quizData.title,
                timeLimitSeconds: quizData.timeLimitSeconds,
                passingScore: quizData.passingScore,
                maxXp: quizData.maxXp,
                isPublished: quizData.isPublished,

                questions: {
                    create: quizData.questions.map((question) => ({
                        questionText: question.questionText,
                        imageUrl: question.imageUrl,
                        timeLimitSeconds: question.timeLimitSeconds,
                        baseXp: question.baseXp,
                        orderIndex: question.orderIndex,

                        options: {
                            create: question.options.map((option) => ({
                                optionText: option.optionText,
                                isCorrect: option.isCorrect,
                                explanation: option.explanation,
                            })),
                        },
                    })),
                },
            },
        });
    }

    console.log('Quiz seeder berhasil dijalankan');
}

main()
    .catch(console.error)
    .finally(async () => {
        await prisma.$disconnect();
    });